name = "remix-cloudflare-template"
compatibility_date = "2024-02-11"
kv_namespaces = [
  { binding = "cache", id = "797d553d08fd4eeaaa116a3f495f7085" },
  { binding = "GOOGLE_API_KEY", id = "a02258fac15b4a4d8fd2244a57492186" }
]

[vars]
GITHUB_OWNER = "edmundhung"
GITHUB_REPO = "remix-cloudflare-template"
